### ISSUE TITLE
which Linux distribution to use as a basis for adding sinit?

### ISSUE THREAD

**Issue by verisokin** [nshp/sinit#2]
Hello.
Which Linux distribution to use as a basis for adding sinit?
What do you recommend Linux distribution for replacement from a regular init?

**Comment by nshp** [comment]
I do not recommend that anyone use this for anything, it's a toy and a code golfing exercise. I booted my laptop using this and Arch Linux from about 2017-2021, but SystemD's expanding reach into the ecosystem has made it harder and harder to replace, and even I don't currently put in the effort to use this.
